version: '3.8'

services:
  vue-app:
    build: .
    container_name: vueflow-container
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm exec vite -- --host   # <-- 수정됨
